### PR TITLE
add annotated image of mc_example for review

### PR DESCRIPTION
**Pull request by jlchang**
Please review the text in this image of the annotated metadata convention compliant metadata example file. Credit to Joy for vastly improving the basic concept and generating a beautiful image. We plan to use it in the upload wizard and the wiki.

mc_compliant_metadata_image

The easiest way to review the image text may be through [this link - original image](https://github.com/broadinstitute/single_cell_portal/blob/56fff3809459cfce438408893eb8aacdd37cd566/site_figures/metadata_file/mc_compliant_metadata_image.jpg)

[update -  cropped image](https://github.com/broadinstitute/single_cell_portal/blob/58a6db3e505e6eba84983c5ba96f46a0a178e7ae/site_figures/metadata_file/mc_compliant_metadata_image_crop.jpg)

[update - full image](https://github.com/broadinstitute/single_cell_portal/blob/58a6db3e505e6eba84983c5ba96f46a0a178e7ae/site_figures/metadata_file/mc_compliant_metadata_image_full.jpg)

This supports SCP-2775

### CODE REVIEW

**Review by eweitz — APPROVED** [review]
So slick!

Is the text big enough to read in the intended display destinations?  Given the image's aspect ratio and available widths in our wiki and upload wizard, it seems the text size will be small.

Copyedits:
* "Non-conventional names": I suggest "Unconventional names", as the [former is rare and the latter is common](https://books.google.com/ngrams/graph?content=non-conventional%2C+unconventional&year_start=1800&year_end=2019&corpus=26&smoothing=3), and the context of "conventional" -- and thus "non-conventional" and "unconventional" -- as being about metadata is established earlier.
* Capitalize first word after colon, or not, consistently: each callout has the form `header: content`.  The first word in `content` is inconsistently capitalized ("Conventional", "denotes", "Cell", "identifiers", etc.). Capitalizing the first word in the content seems best to me, but if you decide otherwise, please ensure consistent uppercase or lowercase in the first letter.
* Append period to "See Required Conventional Metadata link (below)".
* "Onotology ID": "Ontology ID"

**Comment by jlchang** [comment]
Thanks for the suggestions, Eric!
> Is the text big enough to read in the intended display destinations? Given the image's aspect ratio and available widths in our wiki and upload wizard, it seems the text size will be small.
I believe the design for the wizard is a scrolling box for the image that allows all the annotated bits to be in frame at the outset.

For the wiki, I'll clip the image to fit the width (clipping to cut of text to indicate that there is more to the file that is not being shown).

**Review by bistline — APPROVED** [review]
I don't have any comments outside of what Eric already mentioned.

**Comment by jlchang** [comment]
> * "Non-conventional names": I suggest "Unconventional names", as the former is rare and the latter is common

I had resisted using "conventional" for quite a while but it does flow better when reading the content of the wiki. I've now changed "non-convention" to "unconventional" in the wiki. I've hesitated in the past to apply the term "unconventional" to what is really "study specific" metadata. "Unconventional" is a more commonly used word but has the connotation of non-standard or not following general practice. The slightly negative connotation has caused me to favor "non-convention" as in `not of the convention` but I'm willing to try "unconventional".

**Pull request merged**
